site: https://www.cdfifund.gov/programs-training/programs/new-markets-tax-credit
program_type: Tax Credit

selectors:
  title: h1
  funding: null
  deadline: null
  eligibility: null

deep_links:
  selector: a[href*='new-markets-tax-credit']
  attribute: href

auto_pdf_detection: true
pdf_min_size: 10240
pdf_max_size: 10485760
exclude_pdf_keywords:
  - newsletter
  - map
  - brochure
