site: https://www.energy.gov/eere/buildings/buildings-funding-opportunities
program_type: DOE Grant

selectors:
  title: h1
  funding: null
  deadline: null
  eligibility: null

deep_links:
  selector: a[href*='funding']
  attribute: href

auto_pdf_detection: true
pdf_min_size: 10240
pdf_max_size: 10485760
exclude_pdf_keywords:
  - newsletter
  - map
  - brochure
