site: https://www.epa.gov/greenhouse-gas-reduction-fund/about-greenhouse-gas-reduction-fund
program_type: Environmental Incentive
selectors:
  title: h1
  funding: null
  deadline: null
  eligibility: null
deep_links:
  selector: a[href*='fund']
  attribute: href
auto_pdf_detection: true
pdf_min_size: 10240
pdf_max_size: 10485760
exclude_pdf_keywords:
- newsletter
- map
- brochure
