site: https://www.hud.gov/hud-partners/grants-info-funding-opps
program_type: Federal Grant
selectors:
  title: h1
  funding: null
  deadline: null
  eligibility: null
deep_links:
  selector: a[href*='funding']
  attribute: href
auto_pdf_detection: true
pdf_min_size: 10240
pdf_max_size: 10485760
exclude_pdf_keywords:
- newsletter
- map
- brochure
