site: https://www.irs.gov/inflation-reduction-act-of-2022
program_type: Inflation Reduction Act
selectors:
  title: h1
  funding: null
  deadline: null
  eligibility: null
deep_links:
  selector: a[href*='inflation']
  attribute: href
auto_pdf_detection: true
pdf_min_size: 10240
pdf_max_size: 10485760
exclude_pdf_keywords:
- newsletter
- map
- brochure
